import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
const root = fileURLToPath(new URL('../..',import.meta.url))
const live = JSON.parse(readFileSync(root+'/docs/v2/p7_live_acceptance.json','utf8'))
const scan = live.checks.real_four_combination_serial_scan
const [a,b] = scan.records.map((r: { run_id: string }) => r.run_id)
const other = live.checks.non_matching_grid_no_ranking.run_b

test('final comparison uses physical geometry, true time axis and a common color scale', async ({ page }) => {
  const errors: string[]=[]; page.on('pageerror',e=>errors.push(e.message))
  await page.goto(`/workspace/compare?a=${a}&b=${b}`)
  await expect(page.getByTestId('comparison-conditions')).toHaveText('同条件比较')
  await expect(page.getByTestId('comparison-color')).toContainText('t=0.04')
  await expect(page.getByTestId('entropy-chart')).toHaveAttribute('data-axis','physical_time')
  const figure=page.locator('canvas[role=img]').first()
  const geometry=await figure.boundingBox()
  expect(Math.abs(geometry!.width-geometry!.height)).toBeLessThan(2)
  const chart=page.getByTestId('entropy-chart')
  await chart.scrollIntoViewIfNeeded(); const box=await chart.boundingBox()
  await page.mouse.move(box!.x+box!.width*.5,box!.y+box!.height*.5)
  await expect(page.getByText(/^模型时间 /).first()).toBeVisible()
  await page.getByLabel('对比变量').selectOption('mach')
  await expect(page.getByLabel('对比变量')).toBeEnabled()
  await page.getByLabel('共同快照时间').selectOption('0')
  await expect(page.getByTestId('comparison-color')).toHaveText(/· t=0$/)
  await expect(figure).toHaveAttribute('aria-label',/t=0，/)
  await page.screenshot({path:root+'/docs/v2/p7_compare_desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:root+'/docs/v2/p7_compare_mobile.png',fullPage:true})
  expect(errors).toEqual([])
})

test('different grids expose protocol differences and suppress metric subtraction', async ({ page }) => {
  await page.goto(`/workspace/compare?a=${a}&b=${other}`)
  await expect(page.getByTestId('comparison-conditions')).toHaveText('非同条件比较')
  await expect(page.getByText('grid.nx',{exact:true})).toBeVisible()
  await expect(page.getByText('非同条件或指标定义/测量时间不一致。',{exact:true})).toHaveCount(3)
  await page.getByLabel('Run B',{exact:true}).fill(b)
  await expect(page.getByTestId('comparison-conditions')).toHaveCount(0)
  await page.getByRole('button',{name:'核查并对比'}).click()
  await expect(page.getByTestId('comparison-conditions')).toHaveText('同条件比较')
})

test('scan confirmation is invalidated on edit and unsupported values never offer submit', async ({ page }) => {
  await page.goto('/workspace/sweeps')
  await page.getByLabel('基础 Run ID').fill(a)
  await page.getByRole('button',{name:'验证扫描配置'}).click()
  await expect(page.getByRole('heading',{name:'确认 4 项扫描'})).toBeVisible()
  await page.getByLabel('总时间预算',{exact:true}).fill('301')
  await expect(page.getByRole('button',{name:'确认并启动扫描'})).toHaveCount(0)
  await page.getByLabel('q_aa 扫描值').fill('5')
  await page.getByRole('button',{name:'验证扫描配置'}).click()
  await expect(page.getByRole('alert')).toContainText('未支持')
  await expect(page.getByRole('button',{name:'确认并启动扫描'})).toHaveCount(0)
  await page.getByLabel('q_aa 扫描值').fill('3.96,13.2')
  await page.getByLabel('总任务预算',{exact:true}).fill('3')
  await page.getByRole('button',{name:'验证扫描配置'}).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByRole('button',{name:'确认并启动扫描'})).toHaveCount(0)
})

test('completed and budget-exhausted scans survive reload with run links and mobile layout', async ({ page }) => {
  await page.goto('/sweeps/'+scan.sweep_id)
  await page.reload()
  await expect(page.getByTestId('sweep-status')).toHaveText('全部完成')
  await expect(page.getByTestId('sweep-progress')).toContainText('成功 4')
  await expect(page.getByRole('button',{name:'取消扫描',exact:true})).toHaveCount(0)
  await page.screenshot({path:root+'/docs/v2/p7_scan_desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.getByRole('link',{name:'对比前两个成功运行'}).click()
  await expect(page.getByTestId('comparison-conditions')).toHaveText('同条件比较')
  await page.goto('/sweeps/'+live.checks.real_time_budget.record.sweep_id)
  await expect(page.getByTestId('sweep-status')).toHaveText('扫描失败')
  await expect(page.getByRole('alert')).toContainText('时间预算已耗尽')
})
