import { test, expect } from '@playwright/test'

test('real provider: three equivalent entries, modified paper draft and unsupported request', async ({ page, request }) => {
  const cases = await (await request.get('/api/v2/cases')).json()
  expect(cases.data.natural_language_available).toBe(true)
  const runs: string[] = []
  page.on('request', req => { if (req.url().includes('/api/v2/runs')) runs.push(req.url()) })
  await page.goto('/experiments/new')
  await page.getByLabel('起始模板').selectOption('case8.paper.D_u')
  await page.getByRole('button', { name: '验证配置', exact: true }).click()
  const hash = await page.getByTestId('config-hash').innerText()
  await page.getByRole('button', { name: '专业参数', exact: true }).click()
  await page.getByRole('button', { name: '验证配置', exact: true }).click()
  await expect(page.getByTestId('config-hash')).toHaveText(hash)
  await page.getByRole('button', { name: '自然语言', exact: true }).click()
  await page.getByLabel('实验要求').fill('使用 Case 8 的 D_u 论文标准模板，保持全部模板参数不变。')
  await page.getByRole('button', { name: '生成配置草稿' }).click()
  await expect(page.getByTestId('config-hash')).toHaveText(hash, { timeout: 40_000 })
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: '确认配置', exact: true }).click()
  await expect(page.getByTestId('config-confirmed')).toContainText('尚未创建 Run')
  await page.getByLabel('实验要求').fill('使用 Case 8 的 D_u 论文标准模板，将 q_at 改为 0，其他参数保持模板不变。')
  await page.getByRole('button', { name: '生成配置草稿' }).click()
  await expect(page.getByTestId('classification')).toHaveText('论文模板 · 自定义参数', { timeout: 40_000 })
  await expect(page.getByTestId('protocol-diff')).toContainText('q_at')
  await page.screenshot({ path: '../docs/v2/p1_builder_live.png', fullPage: true })
  await page.getByLabel('实验要求').fill('使用 Case 8 的 D_u 论文模板，epsilon=0.0001。')
  await page.getByRole('button', { name: '生成配置草稿' }).click()
  await expect(page.getByTestId('natural-language-draft')).toContainText('未支持', { timeout: 40_000 })
  await expect(page.getByTestId('config-hash')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '启动求解', exact: true })).toBeDisabled()
  expect(runs).toEqual([])
})
