"""Window 1 implements this boundary; bootstrap never opens scientific files."""
from typing import Protocol, runtime_checkable

from backend.models import (CapabilityList, ConfigList, EntropyHistory, EvidenceRecord,
                            Experiment, FieldResponse, FieldSnapshot, MetricCollection,
                            ResultProvenance, ScalarSeries, ScientificArray, SnapshotIndex)


@runtime_checkable
class Case8AdapterProtocol(Protocol):
    def describe_experiment(self) -> Experiment: ...
    def list_configs(self) -> ConfigList: ...
    def describe_capabilities(self) -> CapabilityList: ...
    def list_snapshots(self, config_id: str) -> SnapshotIndex: ...
    def load_snapshot_metadata(self, config_id: str, snapshot_index: int) -> FieldSnapshot: ...
    def load_field(self, config_id: str, snapshot_index: int, field_id: str) -> FieldResponse: ...
    def load_array(self, result_id: str, array_id: str) -> ScientificArray: ...
    def load_entropy_history(self, config_id: str, *, series: tuple[str, ...] | None = None,
                             offset: int = 0, limit: int = 2000) -> EntropyHistory: ...
    def load_scalar_series(self, config_id: str, series_id: str, *, offset: int = 0,
                           limit: int = 2000) -> ScalarSeries: ...
    def load_metrics(self, config_id: str, *, metric_id: str | None = None,
                     snapshot_index: int | None = None) -> MetricCollection: ...
    def load_evidence(self, evidence_id: str) -> EvidenceRecord: ...
    def load_provenance(self, result_id: str) -> ResultProvenance: ...
