import fs from 'node:fs';import path from 'node:path';import { fileURLToPath } from 'node:url';import {createRequire} from 'node:module';
const root=fileURLToPath(new URL('../../',import.meta.url));const require=createRequire(path.join(root,'frontend/package.json'));const {chromium}=require('@playwright/test');
const base=process.env.POLISH_UI_URL??'http://127.0.0.1:4410';const width=Number(process.env.POLISH_QA_WIDTH??1920);const height=width===1920?1080:844;const out=path.join(root,'.cache/polish01',String(width));fs.mkdirSync(out,{recursive:true});
const routes=['/','/home',...Array.from({length:7},(_,i)=>`/explore?scene=${i+1}`),'/lab','/lab/mechanism',...['case8','gate','entropy-closure','spectrum','modal-validation','cylinder'].map(id=>'/lab/experiments/'+id),'/cross-flow','/evidence','/evidence?section=GAPS','/evidence?section=HISTORY','/evidence/ev.case8.D_u.allocation',...['flow','entropy','allocation','metrics','evidence'].map(tab=>'/lab/experiments/case8?config=D_u&tab='+tab),...['flow','entropy','sectors','metrics','evidence'].map(tab=>'/lab/experiments/cylinder?config=D_u&tab='+tab),...['semi-discrete','fully-discrete','evidence'].map(tab=>'/lab/experiments/entropy-closure?run=D_u-cfl-0.05&tab='+tab)];
routes.push('/lab/mechanism?source_scene=3','/lab/experiments/spectrum?spectral_q=spectrum.q-0.396&spectral_mode=8','/lab/experiments/modal-validation?spectral_q=spectrum.q-0.396&spectral_mode=8&spectral_run=modal-validation.m08_q0p396_eps1e-04','/evidence/ev.mechanism.theory-implementation','/evidence/evidence.spectral.spectrum.q-0.396.mode-08','/evidence/evidence.spectral.spectrum.q-0.396.mode-08.right.rank-00.complex_vector.stored_vector','/evidence/evidence.spectral.modal-validation.m01_q0p000_eps1e-04.history','/evidence/ev.missing.cylinder-cumulative2d');
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width,height}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];
try{for(const [i,route] of routes.entries()){await page.goto(base+route);await page.waitForLoadState('networkidle');await page.waitForTimeout(250);
const audit=await page.locator('body').evaluate(el=>{const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode()){const s=w.currentNode.textContent.trim();if(/\b[a-zA-Z]{3,}\s+[a-zA-Z]{3,}\b/.test(s))a.push(s);}return {residual:[...new Set(a)],width:innerWidth,scroll:document.documentElement.scrollWidth,overflowElements:[...el.querySelectorAll('*')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1&&getComputedStyle(e).position!=='absolute';}).slice(0,10).map(e=>({tag:e.tagName,testid:e.getAttribute('data-testid'),class:e.className,text:e.textContent.slice(0,90)}))};});
const name=String(i).padStart(2,'0')+'.png';await page.screenshot({path:path.join(out,name)});const visibleText=await page.locator('body').innerText();fs.writeFileSync(path.join(out,name.replace('.png','.txt')),visibleText);const englishActions=await page.locator('button,a,label,option').evaluateAll(elements=>[...new Set(elements.map(e=>e.textContent.trim()).filter(t=>/[A-Za-z]/.test(t)))]);results.push({route,title:await page.title(),screenshot:name,englishActions,...audit});console.log(route,JSON.stringify({residual:audit.residual,scroll:audit.scroll}));}
if(width===1920&&process.env.POLISH_QA_FOCUS==='1'){
  const focus=path.join(root,'.cache/polish01/focus');fs.mkdirSync(focus,{recursive:true});
  for(const [route,id] of [['/lab/experiments/case8?config=D_u&tab=entropy','entropy-chart'],['/lab/experiments/modal-validation?spectral_q=spectrum.q-0.396&spectral_mode=8&spectral_run=modal-validation.m08_q0p396_eps1e-04','growth-validation-canvas'],['/lab/experiments/spectrum?spectral_q=spectrum.q-0.396&spectral_mode=8','eigenmode-canvas'],['/lab/experiments/cylinder?config=D_u&tab=entropy','cylinder-entropy-chart'],['/lab/experiments/cylinder?config=D_u&tab=sectors','angular-sector-chart'],['/evidence/ev.case8.D_u.allocation','evidence-definitions']]){
    await page.goto(base+route);await page.waitForLoadState('networkidle');const el=page.getByTestId(id);await el.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(focus,id+'.png')});
    if(id==='entropy-chart'){const r=await el.boundingBox();await page.mouse.move(r.x+r.width*.55,r.y+r.height*.5);await page.waitForTimeout(300);await page.screenshot({path:path.join(focus,id+'-tooltip.png')});}
  }
}
fs.writeFileSync(path.join(out,'browser-audit.json'),JSON.stringify({base,viewport:{width,height},results,errors},null,2));
if(errors.length||results.some(r=>r.scroll>width||r.residual.length))throw new Error('Browser audit failed: review browser-audit.json');
}finally{await browser.close();}
